modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="create_crushing_recipe_ci_test"
version="1.0.0"
displayName="Create Crushing Recipe CI Test"
authors="zachsem"
description='''CI-only runtime assertions for Create Crushing Recipe Fix.'''

[[dependencies.create_crushing_recipe_ci_test]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_crushing_recipe_ci_test]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
