plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'io.github.zachsem'
version = '1.0.0'

base {
    archivesName = 'create-crushing-recipe-ci-test'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.18.2'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.18.2-40.3.0'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': 'create_crushing_recipe_ci_test',
            'Specification-Vendor': 'zachsem',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'zachsem'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
